Implement better design issue15
Vanjaman/InDa-Project pull request #18
Opened 2022-05-02 10:23 UTC by vin023

Vad tycker du om hur det ser ut nu? Jag gjorde interfacet lite mindre.

2022-05-02 10:24 UTC, vin023 commented
Nya versionerna av filerna ska användas

2022-05-02 10:50 UTC, Vanjaman requested changes
Ändringarna du gjort ser bra ut! Den blå kolumnen som var till höger om skärmen verkar vara borta! Innan vi pushar det här till main, tror du du kan fixa så att hela sidan får plats på skärmen så att man slipper scrolla för att se footern? Har skapat issue #19 för det.

2022-05-02 15:36 UTC, vin023 commented
Jag har gjort lite ändringar, se discord för mer info.

2022-05-03 13:14 UTC, Vanjaman approved these changes
Seems good!

2022-05-03 13:19 UTC, merged